simpleweb_bugsnag_test_exception:
    pattern: /exception
    defaults: { _controller: SimplewebBugsnagBundle:Default:exception }

simpleweb_bugsnag_test_error:
    pattern: /error
    defaults: { _controller: SimplewebBugsnagBundle:Default:error }
